// Package mime defines common MIME Types listed in: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
// The complete list is available at: https://www.iana.org/assignments/media-types/media-types.xhtml
//
// File extensions that support both audio and video content are suffixed with either an "a" or "v" to differentiate between the MIME Types,
// except for 3GP which is prefixed with either "A" or "V" (because they start with a number).
package mime

const (
	charset = "; charset=utf8"

	A3GP  = "audio/3gpp"
	V3GP  = "video/3gpp"
	A3GP2 = "audio/3gpp2"
	V3GP2 = "video/3gpp2"

	AAC    = "audio/aac"
	ABW    = "application/x-abiword"
	ARC    = "application/x-freearc"
	AVI    = "video/x-msvideo"
	AZW    = "application/vnd.amazon.ebook"
	BIN    = "application/octet-stream"
	BMP    = "image/bmp"
	BZ     = "application/x-bzip"
	BZ2    = "application/x-bzip2"
	CSH    = "application/x-csh"
	CSS    = "text/css" + charset
	CSV    = "text/csv"
	DOC    = "application/msword"
	DOCX   = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	EOT    = "application/vnd.ms-fontobject"
	EPUB   = "application/epub+zip"
	FLAC   = "audio/flac"
	GZ     = "application/gzip"
	GIF    = "image/gif"
	HTML   = "text/html" + charset
	ICO    = "image/vnd.microsoft.icon"
	ICS    = "text/calendar"
	JAR    = "application/java-archive"
	JPG    = "image/jpeg"
	JS     = "text/javascript"
	JSON   = "application/json"
	JSONLD = "application/ld+json"
	MID    = "audio/midi"
	MIDI   = "audio/x-midi"
	MP3    = "audio/mpeg"
	MP4a   = "audio/mp4"
	MP4v   = "video/mp4"
	MPEG   = "video/mpeg"
	MPKG   = "application/vnd.apple.installer+xml"
	ODP    = "application/vnd.oasis.opendocument.presentation"
	ODS    = "application/vnd.oasis.opendocument.spreadsheet"
	ODT    = "application/vnd.oasis.opendocument.text"
	OGA    = "audio/ogg"
	OGV    = "video/ogg"
	OGX    = "application/ogg"
	OPUS   = "audio/opus"
	OTF    = "font/otf"
	PNG    = "image/png"
	PDF    = "application/pdf"
	PHP    = "application/x-httpd-php"
	PPT    = "application/vnd.ms-powerpoint"
	PPTX   = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	RAR    = "application/vnd.rar"
	RTF    = "application/rtf"
	SH     = "application/x-sh"
	SVG    = "image/svg+xml"
	SWF    = "application/x-shockwave-flash"
	TAR    = "application/x-tar"
	TIF    = "image/tiff"
	TS     = "video/mp2t"
	TTF    = "font/ttf"
	TXT    = "text/plain"
	VSD    = "application/vnd.visio"
	WAV    = "audio/wav"
	WEBMa  = "audio/webm"
	WEBMv  = "video/webm"
	WEBP   = "image/webp"
	WOFF   = "font/woff"
	WOFF2  = "font/woff2"
	XHTML  = "application/xhtml+xml"
	XLS    = "application/vnd.ms-excel"
	XLSX   = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	XML    = "text/xml"        // If readable from casual users (RFC 3023, section 3).
	XMLA   = "application/xml" // If not readable from casual users (RFC 3023, section 3).
	XUL    = "application/vnd.mozilla.xul+xml"
	ZIP    = "application/zip"
	ZIP7   = "application/x-7z-compressed"
)
