// Package edg contains constants for how many edges (sides) geometric shapes have.
package edg

const (
	Triangle           = 3
	Square             = 4
	Rectangle          = Square
	Quadrilateral      = Square
	Pentagon           = 5
	Hexagon            = 6
	Heptagon           = 7
	Octagon            = 8
	Nonagon            = 9
	Decagon            = 10
	Hendecagon         = 11
	Dodecagon          = 12
	Tridecagon         = 13
	Tetradecagon       = 14
	Pentadecagon       = 15
	Hexadecagon        = 16
	Heptadecagon       = 17
	Octadecagon        = 18
	Enneadecagon       = 19
	Icosagon           = 20
	Icosikaihenagon    = 21
	Icosikaidigon      = 22
	Icositrigon        = 23
	Icositetragon      = 24
	Icosikaipentagon   = 25
	Icosikaihexagon    = 26
	Icosikaiheptagon   = 27
	Icosikaioctagon    = 28
	Icosikaienneagon   = 29
	Triacontagon       = 30
	Triacontahenagon   = 31
	Triacontadigon     = 32
	Triacontatrigon    = 33
	Triacontatetragon  = 34
	Triacontapentagon  = 35
	Triacontahexagon   = 36
	Triacontaheptagon  = 37
	Triacontaoctagon   = 38
	Triacontaenneagon  = 39
	Tetracontagon      = 40
	Tetracontahenagon  = 41
	Tetracontadigon    = 42
	Tetracontatrigon   = 43
	Tetracontatetragon = 44
	Tetracontapentagon = 45
	Tetracontahexagon  = 46
	Tetracontaheptagon = 47
	Tetracontaoctagon  = 48
	Tetracontaenneagon = 49
	Pentacontagon      = 50
	Pentacontahenagon  = 51
	Pentacontadigon    = 52
	Pentacontatrigon   = 53
	Pentacontatetragon = 54
	Pentacontapentagon = 55
	Pentacontahexagon  = 56
	Pentacontaheptagon = 57
	Pentacontaoctagon  = 58
	Pentacontaenneagon = 59
	Hexacontagon       = 60
	Hexacontahenagon   = 61
	Hexacontadigon     = 62
	Hexacontatrigon    = 63
	Hexacontatetragon  = 64
	Hexacontapentagon  = 65
	Hexacontahexagon   = 66
	Hexacontaheptagon  = 67
	Hexacontaoctagon   = 68
	Hexacontaenneagon  = 69
	Heptacontagon      = 70
	Heptacontahenagon  = 71
	Heptacontadigon    = 72
	Heptacontatrigon   = 73
	Heptacontatetragon = 74
	Heptacontapentagon = 75
	Heptacontahexagon  = 76
	Heptacontaheptagon = 77
	Heptacontaoctagon  = 78
	Heptacontaenneagon = 79
	Octacontagon       = 80
	Octacontahenagon   = 81
	Octacontadigon     = 82
	Octacontatrigon    = 83
	Octacontatetragon  = 84
	Octacontapentagon  = 85
	Octacontahexagon   = 86
	Octacontaheptagon  = 87
	Octacontaoctagon   = 88
	Octacontaenneagon  = 89
	Enneacontagon      = 90
	Enneacontahenagon  = 91
	Enneacontadigon    = 92
	Enneacontatrigon   = 93
	Enneacontatetragon = 94
	Enneacontapentagon = 95
	Enneacontahexagon  = 96
	Enneacontaheptagon = 97
	Enneacontaoctagon  = 98
	Enneacontaenneagon = 99
	Hectogon           = 100
	Hectahenagon       = 101
	Hectadigon         = 102
	Hectatrigon        = 103
	Hectatetragon      = 104
	Hectapentagon      = 105
	Hectahexagon       = 106
	Hectaheptagon      = 107
	Hectaoctagon       = 108
	Hectaenneagon      = 109
	Dihectogon         = 200
	Trihectogon        = 300
	Tetrahectogon      = 400
	Pentahectogon      = 500
	Hexahectogon       = 600
	Heptahectogon      = 700
	Octahectogon       = 800
	Enneahectogon      = 900
	Chiliagon          = 1000
	Myriagon           = 10000
	Megagon            = 1000000

	// Star polygons.

	Diamond           = Square
	Tristar           = Triangle * 2
	Triquetra         = Tristar
	Tetragram         = Square * 2
	Pentagram         = Pentagon * 2
	Hexagram          = Hexagon * 2
	Heptagram         = Heptagon * 2
	Octagram          = Octagon * 2
	Enneagram         = Nonagon * 2
	Decagram          = Decagon * 2
	Hendecagram       = Hendecagon * 2
	Dodecagram        = Dodecagon * 2
	Tridecagram       = Tridecagon * 2
	Tetradecagram     = Tetradecagon * 2
	Pentadecagram     = Pentadecagon * 2
	Hexadecagram      = Hexadecagon * 2
	Heptadecagram     = Heptadecagon * 2
	Octadecagram      = Octadecagon * 2
	Enneadecagram     = Enneadecagon * 2
	Icosagram         = Icosagon * 2
	Icosikaihenagram  = Icosikaihenagon * 2
	Icosikaidigram    = Icosikaidigon * 2
	Icositrigram      = Icositrigon * 2
	Icositetragram    = Icositetragon * 2
	Icosikaipentagram = Icosikaipentagon * 2
	Icosikaihexagram  = Icosikaihexagon * 2
	Icosikaiheptagram = Icosikaiheptagon * 2
	Icosikaioctagram  = Icosikaioctagon * 2
	Icosikaienneagram = Icosikaienneagon * 2
	Triacontagram     = Triacontagon * 2
	Tetracontagram    = Tetracontagon * 2
	Pentacontagram    = Pentacontagon * 2
	Hexacontagram     = Hexacontagon * 2
	Heptacontagram    = Heptacontagon * 2
	Octacontagram     = Octacontagon * 2
	Enneacontagram    = Enneacontagon * 2
	Hectogram         = Hectogon * 2
	Dihectogram       = Dihectogon * 2
	Trihectogram      = Trihectogon * 2
	Tetrahectogram    = Tetrahectogon * 2
	Pentahectogram    = Pentahectogon * 2
	Hexahectogram     = Hexahectogon * 2
	Heptahectogram    = Heptahectogon * 2
	Octahectogram     = Octahectogon * 2
	Enneahectogram    = Enneahectogon * 2
	Chiliagram        = Chiliagon * 2
	Myriagram         = Myriagon * 2
	Megagram          = Megagon * 2
)
