// Package edg contains constants for how many edges (sides, vertices, points or corners) geometric shapes have.
package edg

const (
	Monogon            = 1
	Digon              = 2
	Triangle           = 3
	Square             = 4
	Rectangle          = Square
	Quadrilateral      = Square
	Pentagon           = 5
	Hexagon            = 6
	Heptagon           = 7
	Octagon            = 8
	Nonagon            = 9
	Decagon            = 10
	Hendecagon         = 11
	Dodecagon          = 12
	Tridecagon         = 13
	Tetradecagon       = 14
	Pentadecagon       = 15
	Hexadecagon        = 16
	Heptadecagon       = 17
	Octadecagon        = 18
	Enneadecagon       = 19
	Icosagon           = 20
	Icosikaihenagon    = 21
	Icosikaidigon      = 22
	Icositrigon        = 23
	Icositetragon      = 24
	Icosikaipentagon   = 25
	Icosikaihexagon    = 26
	Icosikaiheptagon   = 27
	Icosikaioctagon    = 28
	Icosikaienneagon   = 29
	Triacontagon       = 30
	Triacontahenagon   = 31
	Triacontadigon     = 32
	Triacontatrigon    = 33
	Triacontatetragon  = 34
	Triacontapentagon  = 35
	Triacontahexagon   = 36
	Triacontaheptagon  = 37
	Triacontaoctagon   = 38
	Triacontaenneagon  = 39
	Tetracontagon      = 40
	Tetracontahenagon  = 41
	Tetracontadigon    = 42
	Tetracontatrigon   = 43
	Tetracontatetragon = 44
	Tetracontapentagon = 45
	Tetracontahexagon  = 46
	Tetracontaheptagon = 47
	Tetracontaoctagon  = 48
	Tetracontaenneagon = 49
	Pentacontagon      = 50
	Pentacontahenagon  = 51
	Pentacontadigon    = 52
	Pentacontatrigon   = 53
	Pentacontatetragon = 54
	Pentacontapentagon = 55
	Pentacontahexagon  = 56
	Pentacontaheptagon = 57
	Pentacontaoctagon  = 58
	Pentacontaenneagon = 59
	Hexacontagon       = 60
	Hexacontahenagon   = 61
	Hexacontadigon     = 62
	Hexacontatrigon    = 63
	Hexacontatetragon  = 64
	Hexacontapentagon  = 65
	Hexacontahexagon   = 66
	Hexacontaheptagon  = 67
	Hexacontaoctagon   = 68
	Hexacontaenneagon  = 69
	Heptacontagon      = 70
	Heptacontahenagon  = 71
	Heptacontadigon    = 72
	Heptacontatrigon   = 73
	Heptacontatetragon = 74
	Heptacontapentagon = 75
	Heptacontahexagon  = 76
	Heptacontaheptagon = 77
	Heptacontaoctagon  = 78
	Heptacontaenneagon = 79
	Octacontagon       = 80
	Octacontahenagon   = 81
	Octacontadigon     = 82
	Octacontatrigon    = 83
	Octacontatetragon  = 84
	Octacontapentagon  = 85
	Octacontahexagon   = 86
	Octacontaheptagon  = 87
	Octacontaoctagon   = 88
	Octacontaenneagon  = 89
	Enneacontagon      = 90
	Enneacontahenagon  = 91
	Enneacontadigon    = 92
	Enneacontatrigon   = 93
	Enneacontatetragon = 94
	Enneacontapentagon = 95
	Enneacontahexagon  = 96
	Enneacontaheptagon = 97
	Enneacontaoctagon  = 98
	Enneacontaenneagon = 99
	Hectogon           = 100
	Hectahenagon       = 101
	Hectadigon         = 102
	Hectatrigon        = 103
	Hectatetragon      = 104
	Hectapentagon      = 105
	Hectahexagon       = 106
	Hectaheptagon      = 107
	Hectaoctagon       = 108
	Hectaenneagon      = 109
	Dihectogon         = 200
	Trihectogon        = 300
	Tetrahectogon      = 400
	Pentahectogon      = 500
	Hexahectogon       = 600
	Heptahectogon      = 700
	Octahectogon       = 800
	Enneahectogon      = 900
	Chiliagon          = 1000
	Myriagon           = 10000
	Megagon            = 1000000

	// Star polygons.

	Diamond             = Square
	Tristar             = 2 * Triangle
	Triquetra           = Tristar
	Tetragram           = 2 * Square
	Pentagram           = 2 * Pentagon
	Hexagram            = 2 * Hexagon
	Heptagram           = 2 * Heptagon
	Octagram            = 2 * Octagon
	Enneagram           = 2 * Nonagon
	Decagram            = 2 * Decagon
	Hendecagram         = 2 * Hendecagon
	Dodecagram          = 2 * Dodecagon
	Tridecagram         = 2 * Tridecagon
	Tetradecagram       = 2 * Tetradecagon
	Pentadecagram       = 2 * Pentadecagon
	Hexadecagram        = 2 * Hexadecagon
	Heptadecagram       = 2 * Heptadecagon
	Octadecagram        = 2 * Octadecagon
	Enneadecagram       = 2 * Enneadecagon
	Icosagram           = 2 * Icosagon
	Icosikaihenagram    = 2 * Icosikaihenagon
	Icosikaidigram      = 2 * Icosikaidigon
	Icositrigram        = 2 * Icositrigon
	Icositetragram      = 2 * Icositetragon
	Icosikaipentagram   = 2 * Icosikaipentagon
	Icosikaihexagram    = 2 * Icosikaihexagon
	Icosikaiheptagram   = 2 * Icosikaiheptagon
	Icosikaioctagram    = 2 * Icosikaioctagon
	Icosikaienneagram   = 2 * Icosikaienneagon
	Triacontagram       = 2 * Triacontagon
	Triacontahenagram   = 2 * Triacontahenagon
	Triacontadigram     = 2 * Triacontadigon
	Triacontatrigram    = 2 * Triacontatrigon
	Triacontatetragram  = 2 * Triacontatetragon
	Triacontapentagram  = 2 * Triacontapentagon
	Triacontahexagram   = 2 * Triacontahexagon
	Triacontaheptagram  = 2 * Triacontaheptagon
	Triacontaoctagram   = 2 * Triacontaoctagon
	Triacontaenneagram  = 2 * Triacontaenneagon
	Tetracontagram      = 2 * Tetracontagon
	Tetracontahenagram  = 2 * Tetracontahenagon
	Tetracontadigram    = 2 * Tetracontadigon
	Tetracontatrigram   = 2 * Tetracontatrigon
	Tetracontatetragram = 2 * Tetracontatetragon
	Tetracontapentagram = 2 * Tetracontapentagon
	Tetracontahexagram  = 2 * Tetracontahexagon
	Tetracontaheptagram = 2 * Tetracontaheptagon
	Tetracontaoctagram  = 2 * Tetracontaoctagon
	Tetracontaenneagram = 2 * Tetracontaenneagon
	Pentacontagram      = 2 * Pentacontagon
	Pentacontahenagram  = 2 * Pentacontahenagon
	Pentacontadigram    = 2 * Pentacontadigon
	Pentacontatrigram   = 2 * Pentacontatrigon
	Pentacontatetragram = 2 * Pentacontatetragon
	Pentacontapentagram = 2 * Pentacontapentagon
	Pentacontahexagram  = 2 * Pentacontahexagon
	Pentacontaheptagram = 2 * Pentacontaheptagon
	Pentacontaoctagram  = 2 * Pentacontaoctagon
	Pentacontaenneagram = 2 * Pentacontaenneagon
	Hexacontagram       = 2 * Hexacontagon
	Hexacontahenagram   = 2 * Hexacontahenagon
	Hexacontadigram     = 2 * Hexacontadigon
	Hexacontatrigram    = 2 * Hexacontatrigon
	Hexacontatetragram  = 2 * Hexacontatetragon
	Hexacontapentagram  = 2 * Hexacontapentagon
	Hexacontahexagram   = 2 * Hexacontahexagon
	Hexacontaheptagram  = 2 * Hexacontaheptagon
	Hexacontaoctagram   = 2 * Hexacontaoctagon
	Hexacontaenneagram  = 2 * Hexacontaenneagon
	Heptacontagram      = 2 * Heptacontagon
	Heptacontahenagram  = 2 * Heptacontahenagon
	Heptacontadigram    = 2 * Heptacontadigon
	Heptacontatrigram   = 2 * Heptacontatrigon
	Heptacontatetragram = 2 * Heptacontatetragon
	Heptacontapentagram = 2 * Heptacontapentagon
	Heptacontahexagram  = 2 * Heptacontahexagon
	Heptacontaheptagram = 2 * Heptacontaheptagon
	Heptacontaoctagram  = 2 * Heptacontaoctagon
	Heptacontaenneagram = 2 * Heptacontaenneagon
	Octacontagram       = 2 * Octacontagon
	Octacontahenagram   = 2 * Octacontahenagon
	Octacontadigram     = 2 * Octacontadigon
	Octacontatrigram    = 2 * Octacontatrigon
	Octacontatetragram  = 2 * Octacontatetragon
	Octacontapentagram  = 2 * Octacontapentagon
	Octacontahexagram   = 2 * Octacontahexagon
	Octacontaheptagram  = 2 * Octacontaheptagon
	Octacontaoctagram   = 2 * Octacontaoctagon
	Octacontaenneagram  = 2 * Octacontaenneagon
	Enneacontagram      = 2 * Enneacontagon
	Enneacontahenagram  = 2 * Enneacontahenagon
	Enneacontadigram    = 2 * Enneacontadigon
	Enneacontatrigram   = 2 * Enneacontatrigon
	Enneacontatetragram = 2 * Enneacontatetragon
	Enneacontapentagram = 2 * Enneacontapentagon
	Enneacontahexagram  = 2 * Enneacontahexagon
	Enneacontaheptagram = 2 * Enneacontaheptagon
	Enneacontaoctagram  = 2 * Enneacontaoctagon
	Enneacontaenneagram = 2 * Enneacontaenneagon
	Hectogram           = 2 * Hectogon
	Hectahenagram       = 2 * Hectahenagon
	Hectadigram         = 2 * Hectadigon
	Hectatrigram        = 2 * Hectatrigon
	Hectatetragram      = 2 * Hectatetragon
	Hectapentagram      = 2 * Hectapentagon
	Hectahexagram       = 2 * Hectahexagon
	Hectaheptagram      = 2 * Hectaheptagon
	Hectaoctagram       = 2 * Hectaoctagon
	Hectaenneagram      = 2 * Hectaenneagon
	Dihectogram         = 2 * Dihectogon
	Trihectogram        = 2 * Trihectogon
	Tetrahectogram      = 2 * Tetrahectogon
	Pentahectogram      = 2 * Pentahectogon
	Hexahectogram       = 2 * Hexahectogon
	Heptahectogram      = 2 * Heptahectogon
	Octahectogram       = 2 * Octahectogon
	Enneahectogram      = 2 * Enneahectogon
	Chiliagram          = 2 * Chiliagon
	Myriagram           = 2 * Myriagon
	Megagram            = 2 * Megagon
)
