// Package edg contains constants for how many edges (sides) geometric shapes have.
package edg

const (
	Triangle         = 3
	Square           = 4
	Rectangle        = Square
	Quadrilateral    = Square
	Pentagon         = 5
	Hexagon          = 6
	Heptagon         = 7
	Octagon          = 8
	Nonagon          = 9
	Decagon          = 10
	Hendecagon       = 11
	Dodecagon        = 12
	Tridecagon       = 13
	Tetradecagon     = 14
	Pentadecagon     = 15
	Hexadecagon      = 16
	Heptadecagon     = 17
	Octadecagon      = 18
	Enneadecagon     = 19
	Icosagon         = 20
	Icosikaihenagon  = 21
	Icosikaidigon    = 22
	Icositrigon      = 23
	Icositetragon    = 24
	Icosikaipentagon = 25
	Icosikaihexagon  = 26
	Icosikaiheptagon = 27
	Icosikaioctagon  = 28
	Icosikaienneagon = 29
	Triacontagon     = 30
	Tetracontagon    = 40
	Pentacontagon    = 50
	Hexacontagon     = 60
	Heptacontagon    = 70
	Octacontagon     = 80
	Enneacontagon    = 90
	Hectogon         = 100
	Dihectogon       = 200
	Trihectogon      = 300
	Tetrahectogon    = 400
	Pentahectogon    = 500
	Hexahectogon     = 600
	Heptahectogon    = 700
	Octahectogon     = 800
	Enneahectogon    = 900
	Chiliagon        = 1000
	Myriagon         = 10000
	Megagon          = 1000000

	// Star polygons.

	Diamond           = Square
	Tristar           = Triangle * 2
	Triquetra         = Tristar
	Tetragram         = Square * 2
	Pentagram         = Pentagon * 2
	Hexagram          = Hexagon * 2
	Heptagram         = Heptagon * 2
	Octagram          = Octagon * 2
	Enneagram         = Nonagon * 2
	Decagram          = Decagon * 2
	Hendecagram       = Hendecagon * 2
	Dodecagram        = Dodecagon * 2
	Tridecagram       = Tridecagon * 2
	Tetradecagram     = Tetradecagon * 2
	Pentadecagram     = Pentadecagon * 2
	Hexadecagram      = Hexadecagon * 2
	Heptadecagram     = Heptadecagon * 2
	Octadecagram      = Octadecagon * 2
	Enneadecagram     = Enneadecagon * 2
	Icosagram         = Icosagon * 2
	Icosikaihenagram  = Icosikaihenagon * 2
	Icosikaidigram    = Icosikaidigon * 2
	Icositrigram      = Icositrigon * 2
	Icositetragram    = Icositetragon * 2
	Icosikaipentagram = Icosikaipentagon * 2
	Icosikaihexagram  = Icosikaihexagon * 2
	Icosikaiheptagram = Icosikaiheptagon * 2
	Icosikaioctagram  = Icosikaioctagon * 2
	Icosikaienneagram = Icosikaienneagon * 2
	Triacontagram     = Triacontagon * 2
	Tetracontagram    = Tetracontagon * 2
	Pentacontagram    = Pentacontagon * 2
	Hexacontagram     = Hexacontagon * 2
	Heptacontagram    = Heptacontagon * 2
	Octacontagram     = Octacontagon * 2
	Enneacontagram    = Enneacontagon * 2
	Hectogram         = Hectogon * 2
	Dihectogram       = Dihectogon * 2
	Trihectogram      = Trihectogon * 2
	Tetrahectogram    = Tetrahectogon * 2
	Pentahectogram    = Pentahectogon * 2
	Hexahectogram     = Hexahectogon * 2
	Heptahectogram    = Heptahectogon * 2
	Octahectogram     = Octahectogon * 2
	Enneahectogram    = Enneahectogon * 2
	Chiliagram        = Chiliagon * 2
	Myriagram         = Myriagon * 2
	Megagram          = Megagon * 2
)
