package clrn_test

import (
	"github.com/speedyhoon/cnst/clrn"
	"strings"
	"testing"
)

func TestUnique(t *testing.T) {
	// Using constants as the keys to prevent duplicate constants from being defined.
	names := map[string]string{
		clrn.AliceBlue:            "AliceBlue",
		clrn.AntiqueWhite:         "AntiqueWhite",
		clrn.Aqua:                 "Aqua",
		clrn.Aquamarine:           "Aquamarine",
		clrn.Azure:                "Azure",
		clrn.Beige:                "Beige",
		clrn.Bisque:               "Bisque",
		clrn.Black:                "Black",
		clrn.BlanchedAlmond:       "BlanchedAlmond",
		clrn.Blue:                 "Blue",
		clrn.BlueViolet:           "BlueViolet",
		clrn.Brown:                "Brown",
		clrn.BurlyWood:            "BurlyWood",
		clrn.CadetBlue:            "CadetBlue",
		clrn.Chartreuse:           "Chartreuse",
		clrn.Chocolate:            "Chocolate",
		clrn.Coral:                "Coral",
		clrn.CornflowerBlue:       "CornflowerBlue",
		clrn.Cornsilk:             "Cornsilk",
		clrn.Crimson:              "Crimson",
		clrn.Cyan:                 "Cyan",
		clrn.DarkBlue:             "DarkBlue",
		clrn.DarkCyan:             "DarkCyan",
		clrn.DarkGoldenrod:        "DarkGoldenrod",
		clrn.DarkGray:             "DarkGray",
		clrn.DarkGreen:            "DarkGreen",
		clrn.DarkGrey:             "DarkGrey",
		clrn.DarkKhaki:            "DarkKhaki",
		clrn.DarkMagenta:          "DarkMagenta",
		clrn.DarkOliveGreen:       "DarkOliveGreen",
		clrn.DarkOrange:           "DarkOrange",
		clrn.DarkOrchid:           "DarkOrchid",
		clrn.DarkRed:              "DarkRed",
		clrn.DarkSalmon:           "DarkSalmon",
		clrn.DarkSeaGreen:         "DarkSeaGreen",
		clrn.DarkSlateBlue:        "DarkSlateBlue",
		clrn.DarkSlateGray:        "DarkSlateGray",
		clrn.DarkSlateGrey:        "DarkSlateGrey",
		clrn.DarkTurquoise:        "DarkTurquoise",
		clrn.DarkViolet:           "DarkViolet",
		clrn.DeepPink:             "DeepPink",
		clrn.DeepSkyBlue:          "DeepSkyBlue",
		clrn.DimGray:              "DimGray",
		clrn.DimGrey:              "DimGrey",
		clrn.DodgerBlue:           "DodgerBlue",
		clrn.Firebrick:            "Firebrick",
		clrn.FloralWhite:          "FloralWhite",
		clrn.ForestGreen:          "ForestGreen",
		clrn.Fuchsia:              "Fuchsia",
		clrn.Gainsboro:            "Gainsboro",
		clrn.GhostWhite:           "GhostWhite",
		clrn.Gold:                 "Gold",
		clrn.Goldenrod:            "Goldenrod",
		clrn.Gray:                 "Gray",
		clrn.Green:                "Green",
		clrn.GreenYellow:          "GreenYellow",
		clrn.Grey:                 "Grey",
		clrn.Honeydew:             "Honeydew",
		clrn.HotPink:              "HotPink",
		clrn.IndianRed:            "IndianRed",
		clrn.Indigo:               "Indigo",
		clrn.Ivory:                "Ivory",
		clrn.Khaki:                "Khaki",
		clrn.Lavender:             "Lavender",
		clrn.LavenderBlush:        "LavenderBlush",
		clrn.LawnGreen:            "LawnGreen",
		clrn.LemonChiffon:         "LemonChiffon",
		clrn.LightBlue:            "LightBlue",
		clrn.LightCoral:           "LightCoral",
		clrn.LightCyan:            "LightCyan",
		clrn.LightGoldenrodYellow: "LightGoldenrodYellow",
		clrn.LightGray:            "LightGray",
		clrn.LightGreen:           "LightGreen",
		clrn.LightGrey:            "LightGrey",
		clrn.LightPink:            "LightPink",
		clrn.LightSalmon:          "LightSalmon",
		clrn.LightSeaGreen:        "LightSeaGreen",
		clrn.LightSkyBlue:         "LightSkyBlue",
		clrn.LightSlateGray:       "LightSlateGray",
		clrn.LightSlateGrey:       "LightSlateGrey",
		clrn.LightSteelBlue:       "LightSteelBlue",
		clrn.LightYellow:          "LightYellow",
		clrn.Lime:                 "Lime",
		clrn.LimeGreen:            "LimeGreen",
		clrn.Linen:                "Linen",
		clrn.Magenta:              "Magenta",
		clrn.Maroon:               "Maroon",
		clrn.MediumAquamarine:     "MediumAquamarine",
		clrn.MediumBlue:           "MediumBlue",
		clrn.MediumOrchid:         "MediumOrchid",
		clrn.MediumPurple:         "MediumPurple",
		clrn.MediumSeaGreen:       "MediumSeaGreen",
		clrn.MediumSlateBlue:      "MediumSlateBlue",
		clrn.MediumSpringGreen:    "MediumSpringGreen",
		clrn.MediumTurquoise:      "MediumTurquoise",
		clrn.MediumVioletRed:      "MediumVioletRed",
		clrn.MidnightBlue:         "MidnightBlue",
		clrn.MintCream:            "MintCream",
		clrn.MistyRose:            "MistyRose",
		clrn.Moccasin:             "Moccasin",
		clrn.NavajoWhite:          "NavajoWhite",
		clrn.Navy:                 "Navy",
		clrn.OldLace:              "OldLace",
		clrn.Olive:                "Olive",
		clrn.OliveDrab:            "OliveDrab",
		clrn.Orange:               "Orange",
		clrn.OrangeRed:            "OrangeRed",
		clrn.Orchid:               "Orchid",
		clrn.PaleGoldenrod:        "PaleGoldenrod",
		clrn.PaleGreen:            "PaleGreen",
		clrn.PaleTurquoise:        "PaleTurquoise",
		clrn.PaleVioletRed:        "PaleVioletRed",
		clrn.PapayaWhip:           "PapayaWhip",
		clrn.PeachPuff:            "PeachPuff",
		clrn.Peru:                 "Peru",
		clrn.Pink:                 "Pink",
		clrn.Plum:                 "Plum",
		clrn.PowderBlue:           "PowderBlue",
		clrn.Purple:               "Purple",
		clrn.RebeccaPurple:        "RebeccaPurple",
		clrn.Red:                  "Red",
		clrn.RosyBrown:            "RosyBrown",
		clrn.RoyalBlue:            "RoyalBlue",
		clrn.SaddleBrown:          "SaddleBrown",
		clrn.Salmon:               "Salmon",
		clrn.SandyBrown:           "SandyBrown",
		clrn.SeaGreen:             "SeaGreen",
		clrn.Seashell:             "Seashell",
		clrn.Sienna:               "Sienna",
		clrn.Silver:               "Silver",
		clrn.SkyBlue:              "SkyBlue",
		clrn.SlateBlue:            "SlateBlue",
		clrn.SlateGray:            "SlateGray",
		clrn.SlateGrey:            "SlateGrey",
		clrn.Snow:                 "Snow",
		clrn.SpringGreen:          "SpringGreen",
		clrn.SteelBlue:            "SteelBlue",
		clrn.Tan:                  "Tan",
		clrn.Teal:                 "Teal",
		clrn.Thistle:              "Thistle",
		clrn.Tomato:               "Tomato",
		clrn.Turquoise:            "Turquoise",
		clrn.Violet:               "Violet",
		clrn.Wheat:                "Wheat",
		clrn.White:                "White",
		clrn.WhiteSmoke:           "WhiteSmoke",
		clrn.Yellow:               "Yellow",
		clrn.YellowGreen:          "YellowGreen",
	}

	t.Run("expected quantity", func(t *testing.T) {
		const expectedQty = 148
		if qty := len(names); qty != expectedQty {
			t.Errorf("have %d color-names, expected %d\n", qty, expectedQty)
		}
	})

	for value, name := range names {
		t.Run(name, func(t *testing.T) {
			if expected := strings.ToLower(name); value != expected {
				t.Errorf("expected color-name `%s`, got `%s`", expected, value)
			}
		})
	}
}
